### PR TITLE
Release 0.0.0

### PR DESCRIPTION
**Pull request by sparverius**
Trying a slightly different approach this time. See srcgen/DISTRIB/Makefile. 

Though I have been thinking that it would be nice to have a separate repo for release.
Currently the development environment without all of these other files is nice and lightweight. Either way works though. 

Let me know your thoughts.

### CODE REVIEW

**Comment by sparverius** [comment]
Also, maybe not all of the files are necessary?

**Comment by sparverius** [comment]
See Makefile_release in the root of the repository. Have not done extensive testing yet though.

**Comment by githwxi** [comment]
Hi Richard,

Thanks for taking the initiative! 

I am thinking about creating a module (NPM) for doing the
packaging and release. In particular, let's document the process
so that other people can join. Would you like to have a discussion
over Skype or Google hangout?

**Comment by githwxi** [comment]
I have now added srcgen/CBOOT.

As for srcgen/DISTRIB, let us move it to a module written for supporting  distribution of ATS-Temptory and more.

**Comment by sparverius** [comment]
Sounds good to me.

**Comment by sparverius** [comment]
What time works for you to discuss?

**Comment by githwxi** [comment]
I am available this afternoon from this point on.

**Comment by sparverius** [comment]
Ok, this seems to be the minimal amount of work needed for the module

https://github.com/sparverius/Temptory-Release

**Comment by sparverius** [comment]
The ideas for the repo Temptory-Release:: 

Steps:
clone ATS-Temptory repo
Bootstrap the cloned repo with config files
compile cloned repo (that now contains the relevant config files) 
...release

**Comment by githwxi** [comment]
Just tried it. Awesome!

Now we need to think of a way to publish the package in npm.
Or maybe not. I suppose that leaving it at Github is fine for now.

How about using Temptory-Release to store all the released packages as
well?
Also, it would be useful to support the release of docker images of such
packages, too.

Cheers!

**Comment by ashalkhakov** [comment]
I don't understand what is going on in this thread but may I ask you humbly to minimize the use of symlinking in the repo to make things simpler for poor Windows users? Symlinking being unsupported in MSYS2 (more to the point, I couldn't get it to work and boy did I try!) is currently the biggest culprit to bringing ATS2 to Windows.

**Comment by sparverius** [comment]
The original proposed may to build ATS-Temptory was adapted from they way in which it is currently done in ATS2. Many files and a whole lot of “chasing pointers”...

Since then I realized how to greatly simplify the process. See:

https://github.com/sparverius/Temptory-Release

And https://github.com/sparverius/Temptory-Release/releases

**Comment by sparverius** [comment]
The only symlink there I believe is that Makefile in the root links to Makefile_build

**Comment by sparverius** [comment]
@ashalkhakov 
It looks like there are no more symlinks in this repository and I also removed all symlinks from ATS-Temptory-release.

**Comment by githwxi** [comment]
I close it for now.

It would be really nice to have something like 'npm temptory' for installing the whole thing.

**Pull request closed without merging**
